---
theme: minima
title: Regal Development
description: This is a personal website dedicated to the projects I work on. Hopefully, you are not too incredibly disappointed... Everybody's trying. ;)

---
