# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Regal Writing
description: A personal blog that helps both of us get the gist.
github_username: c-a-s-t-l-e

# Email and twitter are optional:
email: castle676767@gmail.com
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: G-FQL6XEGK4Z

# Edit the navigation links:
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Resume"
    url: /resume/
    title: "Browse by Category"
    url: /browse_by_category/
  - title: "Search"
    url: /search.html

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: GFM
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
