theme: jekyll-theme-minimal
title: Regal Development
description: This is a personal site dedicated the projects I work on. Hopefully, you are not to incredibly disappointed... Everybody's trying. ;)
